#!/bin/sh
sage < script1424 > saida1424_id5_ORD
sage: [Z/3 + Z/3 + Z/3 + Z/3, Z/63 + Z/63, Z/132 + Z/132]
sage: [Z/3 + Z/3 + Z/3 + Z/3, Z/213 + Z/213, Z/432 + Z/432]
sage: volume
sage: 24.8073697340
sage: 24.807369734
sage: 
Exiting Sage (CPU time 0m0.42s, Wall time 0m29.01s).
______________________________________________________________


sage < script1516 > saida1516_id5_ORD
sage: [Z/229773, Z/1110327, Z/3018207, Z/3699687]
sage: [Z/3 + Z/1299909, Z/126627, Z/1052067, Z/4117827]
sage: [Z/229773, Z/1110327, Z/3018207, Z/3699687]
sage: [Z/3 + Z/1299909, Z/126627, Z/1052067, Z/4117827]
sage: volume
sage: 28.375305555
sage: 28.3753055549
sage: 28.375305555
sage: 28.3753055549
sage: 
Exiting Sage (CPU time 0m1.55s, Wall time 2m17.75s).
______________________________________________________________


sage < script1642 > saida1642_id5_ORD
sage: [Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/4 + Z/8,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/4 + Z/264,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/10,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/9576,
 Z/2 + Z/2 + Z/2 + Z/498,
 Z/2 + Z/2 + Z/2 + Z/1746,
 Z/2 + Z/2 + Z/2 + Z/1746,
 Z/2 + Z/2 + Z/4 + Z/4 + Z/32,
 Z/2 + Z/2 + Z/4 + Z/60 + Z,
 Z/2 + Z/2 + Z/4 + Z/64,
 Z/2 + Z/2 + Z/4 + Z/64,
 Z/2 + Z/2 + Z/6 + Z/12,
 Z/2 + Z/2 + Z/18 + Z/18,
 Z/2 + Z/2 + Z/18 + Z/18,
 Z/2 + Z/2 + Z/24 + Z + Z,
 Z/2 + Z/2 + Z/48870,
 Z/2 + Z/2 + Z/49208,
 Z/2 + Z/2 + Z/49208,
 Z/2 + Z/6 + Z/204,
 Z/2 + Z/6 + Z/714,
 Z/2 + Z/22 + Z/118360]
sage: [Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/8 + Z/56,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/4 + Z/4664,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/286,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/702,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/702,
 Z/2 + Z/2 + Z/2 + Z/78 + Z,
 Z/2 + Z/2 + Z/2 + Z/1104,
 Z/2 + Z/2 + Z/4 + Z/4 + Z,
 Z/2 + Z/2 + Z/4 + Z/20,
 Z/2 + Z/2 + Z/4 + Z/20,
 Z/2 + Z/2 + Z/4 + Z/324,
 Z/2 + Z/2 + Z/4 + Z/324,
 Z/2 + Z/2 + Z/6 + Z/12,
 Z/2 + Z/2 + Z/24 + Z + Z,
 Z/2 + Z/2 + Z/1530,
 Z/2 + Z/2 + Z/58698]
sage: [Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/4 + Z/8,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/4 + Z/264,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/10,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/9576,
 Z/2 + Z/2 + Z/2 + Z/498,
 Z/2 + Z/2 + Z/2 + Z/1746,
 Z/2 + Z/2 + Z/2 + Z/1746,
 Z/2 + Z/2 + Z/4 + Z/4 + Z/32,
 Z/2 + Z/2 + Z/4 + Z/60 + Z,
 Z/2 + Z/2 + Z/4 + Z/64,
 Z/2 + Z/2 + Z/4 + Z/64,
 Z/2 + Z/2 + Z/6 + Z/12,
 Z/2 + Z/2 + Z/18 + Z/18,
 Z/2 + Z/2 + Z/18 + Z/18,
 Z/2 + Z/2 + Z/24 + Z + Z,
 Z/2 + Z/2 + Z/48870,
 Z/2 + Z/2 + Z/49208,
 Z/2 + Z/2 + Z/49208,
 Z/2 + Z/6 + Z/204,
 Z/2 + Z/6 + Z/714,
 Z/2 + Z/22 + Z/118360]
sage: [Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/8 + Z/56,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/2 + Z/16 + Z,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/4 + Z/4664,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/286,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/702,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/702,
 Z/2 + Z/2 + Z/2 + Z/78 + Z,
 Z/2 + Z/2 + Z/2 + Z/1104,
 Z/2 + Z/2 + Z/4 + Z/4 + Z,
 Z/2 + Z/2 + Z/4 + Z/20,
 Z/2 + Z/2 + Z/4 + Z/20,
 Z/2 + Z/2 + Z/4 + Z/324,
 Z/2 + Z/2 + Z/4 + Z/324,
 Z/2 + Z/2 + Z/6 + Z/12,
 Z/2 + Z/2 + Z/24 + Z + Z,
 Z/2 + Z/2 + Z/1530,
 Z/2 + Z/2 + Z/58698]
sage: volume
sage: 32.9085657755
sage: 32.908565776
sage: 32.908565776
sage: 32.9085657755
sage: 
Exiting Sage (CPU time 0m5.49s, Wall time 3m36.56s).
______________________________________________________________


sage < script16141 > saida16141_id5_ORD
sage: [Z/2 + Z/4285014, Z/2 + Z/4285014, Z/3 + Z/3 + Z/3 + Z/3]
sage: [Z/2 + Z/3357564, Z/2 + Z/3357564, Z/3 + Z/3 + Z/3 + Z/3]
sage: volume
sage: 30.7074870213
sage: 30.707487021
sage: 
Exiting Sage (CPU time 0m0.90s, Wall time 1m18.90s).
______________________________________________________________


sage < script16142 > saida16142_id5_ORD
sage: [Z/2 + Z/2 + Z/2 + Z/2 + Z/4,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/4,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/12 + Z/12 + Z,
 Z/2 + Z/2 + Z/168,
 Z/2 + Z/2 + Z/168,
 Z/2 + Z/2 + Z/12804,
 Z/2 + Z/2 + Z/12804,
 Z/2 + Z/2 + Z/42006,
 Z/2 + Z/2 + Z/42006,
 Z/3 + Z/3 + Z,
 Z/3 + Z/3 + Z,
 Z/3 + Z/3 + Z/162,
 Z/3 + Z/3 + Z/162,
 Z/3 + Z/3 + Z/1668,
 Z/3 + Z/3 + Z/1668,
 Z/3 + Z/84,
 Z/3 + Z/84,
 Z/3 + Z/990,
 Z/3 + Z/990,
 Z/3 + Z/13548,
 Z/3 + Z/13548,
 Z/3 + Z/26358,
 Z/3 + Z/26358,
 Z/4 + Z/4 + Z,
 Z/4 + Z/4 + Z,
 Z/6 + Z/6 + Z,
 Z/57 + Z/57 + Z,
 Z/7392,
 Z/7392]
sage: [Z/2 + Z/2 + Z/2 + Z/2 + Z/4,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/4,
 Z/2 + Z/2 + Z/2 + Z/2 + Z/12 + Z/12 + Z,
 Z/3 + Z/3 + Z,
 Z/3 + Z/3 + Z,
 Z/3 + Z/468,
 Z/3 + Z/468,
 Z/3 + Z/1632,
 Z/3 + Z/1632,
 Z/3 + Z/3618,
 Z/3 + Z/3618,
 Z/3 + Z/47694,
 Z/3 + Z/47694,
 Z/4 + Z/4 + Z,
 Z/4 + Z/4 + Z,
 Z/6 + Z/6 + Z/6324,
 Z/6 + Z/6 + Z/6324,
 Z/6 + Z/6 + Z/61254,
 Z/6 + Z/6 + Z/61254,
 Z/9 + Z/9 + Z,
 Z/126 + Z/126 + Z,
 Z/4200,
 Z/4200,
 Z/10422,
 Z/10422,
 Z/13344,
 Z/13344,
 Z/14454,
 Z/14454]
sage: volume
sage: 30.729338019
sage: 30.7293380190
sage: 
Exiting Sage (CPU time 0m47.88s, Wall time 233m45.92s).

______________________________________________________________


T631 tem triangulação errada, é 01,01 CORRIGIR!!
Resultado abaixo já tem a boa triangulação.

sage < script16233 > saida16233_id5_ORD
sage: [Z/4 + Z/4 + Z/36 + Z/36, Z/21 + Z/21]
sage: [Z/2 + Z/2 + Z/258 + Z/258, Z/171 + Z/171]
sage: volume
sage: 29.624669407
sage: 29.6246694067
sage: 
Exiting Sage (CPU time 0m1.68s, Wall time 1m5.63s).

______________________________________________________________


















______________________________________________________________

Muito pesado... aborted

sage < script16140 > saida16140_id6_ORD
sage: import snappy
sage: A=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16140_T423.tri')
sage: B=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16140_T444.tri')
sage: C=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16140_T445.tri')
sage: D=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16140_T473.tri')
sage: A
unnamed link(0,1)(0,1)
sage: B
unnamed link(0,1)(0,1)
sage: C
unnamed link(0,1)(0,1)
sage: D
unnamed link(0,1)(0,1)
sage: A.volume()
30.587901596
sage: B.volume()
30.587901596
sage: C.volume()
30.587901596
sage: D.volume()
30.5879015956

______________________________________________________________

Muito pesado...aborted

sage < script1522 > saida1522_id6_ORD

sage: A=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1522_T128.tri')
sage: B=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1522_T141.tri')
sage: C=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1522_T186.tri')
sage: D=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1522_T206.tri')
sage: A
unnamed link(0,1)(-1,1)
sage: B
unnamed link(0,1)(-1,1)
sage: C
unnamed link(0,1)(1,1)
sage: D
unnamed link(0,1)(1,1)
sage: A.volume()
27.9322198834
sage: B.volume()
27.932219883
sage: C.volume()
27.9322198834
sage: D.volume()
27.9322198834



sage: [Z/3 + Z/6 + Z + Z, Z/207, Z/3 + Z/3 + Z, Z/3 + Z/6 + Z + Z, Z/2 + Z/234, Z/5571, Z/9, Z/5637, Z/2 + Z/162, Z/2 + Z/414, Z/2 + Z/1086, Z/6 + Z/6 + Z/10800, Z/3 + Z/6 + Z/18 + Z/720, Z/6 + Z/6 + Z/1296, Z/3 + Z/6 + Z/18 + Z/720]

sage: [Z/2 + Z/2394, Z/6 + Z/1482, Z/3 + Z/3 + Z, Z/6 + Z/1386, Z/3 + Z/3921, Z/2115, Z/9, Z/3 + Z/6 + Z + Z, Z/3 + Z/6 + Z + Z, Z/3 + Z/6 + Z/18 + Z/720, Z/3 + Z/6 + Z/18 + Z/720, Z/6 + Z/6 + Z/5328, Z/207, Z/6 + Z/6 + Z/144, Z/3 + Z/2439]

sage: [Z/3 + Z/3 + Z, Z/2 + Z/414, Z/2 + Z/1086, Z/5637, Z/3 + Z/6 + Z + Z, Z/3 + Z/6 + Z + Z, Z/5571, Z/3 + Z/6 + Z/18 + Z/720, Z/3 + Z/6 + Z/18 + Z/720, Z/2 + Z/162, Z/2 + Z/234, Z/9, Z/207, Z/6 + Z/6 + Z/10800, Z/6 + Z/6 + Z/1296]

sage: [Z/3 + Z/3 + Z, Z/6 + Z/1482, Z/6 + Z/1386, Z/3 + Z/6 + Z + Z, Z/9, Z/207, Z/2 + Z/2394, Z/3 + Z/6 + Z + Z, Z/2115, Z/3 + Z/2439, Z/3 + Z/3921, Z/6 + Z/6 + Z/144, Z/6 + Z/6 + Z/5328, Z/3 + Z/6 + Z/18 + Z/720, Z/3 + Z/6 + Z/18 + Z/720]

______________________________________________________________

Muito pesado... aborted

sage < script1519 > saida1519_id6_ORD
sage: A=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1519_T122.tri')
sage: B=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1519_T148.tri')
sage: C=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1519_T188.tri')
sage: D=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/1519_T208.tri')
sage: A
unnamed link(0,1)(-1,1)
sage: B
unnamed link(0,1)(-1,1)
sage: C
unnamed link(0,1)(1,1)
sage: D
unnamed link(0,1)(1,1)
sage: A.volume() 
27.670218370
sage: B.volume()
27.670218370
sage: C.volume()
27.670218370
sage: D.volume()
27.670218370


sage: [Z/549,
 Z/549,
 Z/531,
 Z/24 + Z,
 Z/2 + Z/2 + Z/15486,
 Z/4716,
 Z/4716,
 Z/3 + Z/3 + Z/6552,
 Z/24 + Z,
 Z/531,
 Z/6 + Z/402,
 Z/2 + Z/894,
 Z/3 + Z/3 + Z/732,
 Z/3 + Z/3 + Z/6552,
 Z/3 + Z/3 + Z/732,
 Z/2 + Z/2 + Z/15486,
 Z/4 + Z/12,
 Z/6 + Z/402,
 Z/4 + Z/12,
 Z/2 + Z/894]
sage: [Z/6 + Z/150,
 Z/6 + Z/162,
 Z/1341,
 Z/2 + Z/2 + Z/114,
 Z/6 + Z/450,
 Z/71496,
 Z/3 + Z/24 + Z,
 Z/4356,
 Z/11025,
 Z/18 + Z/450,
 Z/3 + Z/3 + Z/51,
 Z/2 + Z/966,
 Z/3 + Z/3 + Z/1302,
 Z/8 + Z/24,
 Z/6 + Z/4842,
 Z/2 + Z/2 + Z/384,
 Z/6 + Z/6 + Z/444,
 Z/6 + Z/138,
 Z/4866,
 Z/66402]
sage: [Z/531,
 Z/531,
 Z/24 + Z,
 Z/24 + Z,
 Z/549,
 Z/549,
 Z/3 + Z/3 + Z/6552,
 Z/4 + Z/12,
 Z/2 + Z/894,
 Z/4716,
 Z/3 + Z/3 + Z/6552,
 Z/3 + Z/3 + Z/732,
 Z/2 + Z/894,
 Z/3 + Z/3 + Z/732,
 Z/4716,
 Z/2 + Z/2 + Z/15486,
 Z/2 + Z/2 + Z/15486,
 Z/6 + Z/402,
 Z/4 + Z/12,
 Z/6 + Z/402]
sage: [Z/6 + Z/138,
 Z/2 + Z/2 + Z/114,
 Z/3 + Z/3 + Z/1302,
 Z/2 + Z/966,
 Z/66402,
 Z/6 + Z/150,
 Z/11025,
 Z/4356,
 Z/4866,
 Z/18 + Z/450,
 Z/1341,
 Z/6 + Z/162,
 Z/3 + Z/3 + Z/51,
 Z/6 + Z/4842,
 Z/6 + Z/450,
 Z/2 + Z/2 + Z/384,
 Z/6 + Z/6 + Z/444,
 Z/3 + Z/24 + Z,
 Z/8 + Z/24,
 Z/71496]
______________________________________________________________

O volume deste está diferente, não entendo porque. Já conferi o link e triangulação (FileRomero).

sage < script16149 > saida16149_id5_ORD
sage: []
sage: []
sage: [Z/3 + Z/12 + Z, Z/3 + Z/12 + Z]
sage: [Z/3 + Z/12 + Z, Z/3 + Z/12 + Z]

sage: import snappy
sage: A=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T437.tri')
sage: B=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T449.tri')
sage: C=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T464.tri')
sage: D=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T537.tri')
sage: A
unnamed link(0,1)(4,1)
sage: B
unnamed link(0,1)(-4,1)
sage: C
unnamed link(0,1)(0,1)
sage: D
unnamed link(0,1)(0,1)
sage: A.volume()
33.464380115
sage: B.volume()
33.464380115
sage: C.volume()
30.867341891
sage: D.volume()
30.8673418910
sage: A=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T437.lnk')
sage: B=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T449.lnk')
sage: C=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T464.lnk')
sage: D=snappy.Manifold('/home/cris/Git/286.T-doubts.paper/SnapPyFiles/3conMono16edges/16149_T537.lnk')
sage: A.volume()                                                                                       
35.1768195057
sage: B.volume()                                                                                       
35.176819506
sage: C.volume()                                                                                       
35.074897760
sage: D.volume()                                                                                       
35.0748977598
