#!/bin/sh
sage < script1424 > saida1424_id5_ORD
echo "1424_id5 finished"
cat saida1424_id5_ORD
sage < script1516 > saida1516_id5_ORD
echo "1516_id5 finished"
cat saida1516_id5_ORD
sage < script1519 > saida1519_id6_ORD
echo "1519_id6 finished"
cat saida1519_id6_ORD
sage < script1522 > saida1522_id6_ORD
echo "1522_id6 finished"
cat saida1522_id6_ORD
sage < script1642 > saida1642_id4_ORD
echo "1642_id4 finished"
cat saida1642_id4_ORD
sage < script1656 > saida1656_id3_ORD
echo "1656_id3 finished"
cat saida1656_id3_ORD
sage < script16140 > saida16140_id6_ORD
echo "16140_id6 finished"
cat saida16140_id6_ORD
sage < script16141 > saida16141_id5_ORD
echo "16141_id5 finished"
cat saida16141_id5_ORD
sage < script16142 > saida16142_id5_ORD
echo "16142_id5 finished"
cat saida16142_id5_ORD
sage < script16149 > saida16149_id5_ORD
echo "16149_id5 finished"
cat saida16149_id5_ORD
sage < script16233 > saida16233_id5_ORD
echo "16233_id5 finished"
cat saida16233_id5_ORD
